services:
  - type: web
    name: lurk
    env: node
    plan: free
    buildCommand: npm ci && cd lurk-backend && npm ci && cd .. && npm run build
    startCommand: node lurk-backend/src/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
