git add render.yamlservices:
  - type: web
    name: image-board
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPLOAD_DIR
        value: /data/uploads
    disk:
      name: uploads
      mountPath: /data/uploads
      sizeGB: 1
